language: node_js
node_js:
    - 6 
install:
    - cd ./software/cloud-dashboard/react-client
    - npm install
    - cd ..
    - cd node-server
    - npm install
    - cd ..
script: 
    - cd react-client
    - npm run test
    - cd ..
    - cd node-server
    - npm run test -- --coverage

